import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :bestnowelixirmysql, BestnowelixirmysqlWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :bestnowelixirmysql, Bestnowelixirmysql.Repo,
       username: "root",
       password: "XZB9O6G8fred.",
       database: "bestnowtech",
       hostname: "127.0.0.1",
       show_sensitive_data_on_connection_error: true,
       pool_size: 10

config :at_ex,
       api_key: "f69a9ac7e25242e426da5b0f4401a33436aa9ec772a8d7b27050d98349f80fcd",
         # When changed to "false" one will use the live endpoint url
       sandbox: true,
       username: "stimapap",
       stk_product_name: "AtEx",
       b2c_product_name: "AtEx",
       b2b_product_name: "AtEx",
       bank_checkout_product_name: "AtEx",
       bank_transfer_product_name: "AtEx",
       card_checkout_product_name: "AtEx"

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :bestnowelixirmysql, BestnowelixirmysqlWeb.Endpoint,
#       ...,
#       url: [host: "example.com", port: 443],
#       https: [
#         ...,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :bestnowelixirmysql, BestnowelixirmysqlWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.
